version: "3"
services:
    blog_gateway:
        container_name: blog_gateway
        image: blog_gateway
        volumes:
            - ./app:/usr/src/app
        # - ./content:/usr/src/app/content

networks:
    default:
        external:
            name: gateway_network
