FROM nginx:latest
EXPOSE 3000
COPY ./docker/nginx.conf /etc/nginx/nginx.conf

FROM node:latest

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies for backend gateway
COPY ./app/package.json /usr/src/app
RUN npm install

# Bundle app source
COPY ./app /usr/src/app

RUN mkdir -p /usr/src/app/frontend
COPY ./app/frontend/package.json /usr/src/app/frontend/package.json
RUN cd frontend && npm install
COPY ./app/frontend /usr/src/app/frontend

RUN cd frontend && npm run build
# Exports
EXPOSE 3000
CMD [ "npm", "run", "start" ]
