version: "3"
services:
    sso_database:
        container_name: sso_database
        image: mongo
        environment:
            # back up admin user in case something goes wrong
            - MONGO_INITDB_DATABASE=ssoAdmin
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=rhinos
        volumes:
            # For the startup script that mongo runs to create a new user
            - ./app/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            # Store the mongo database on the host to make it persistent between container restarts
            - ./mongo-volume:/data/db
        ports:
            - "27018:27017"
        expose:
            - 27018
            - 27017
        command: mongod --auth --quiet
        logging:
            driver: none
