version: "3"
services:
    sso_test_client:
        container_name: sso_test_client
        image: sso_test_client
        environment:
            - VIRTUAL_HOST=test.rolandw.dev
            - LETSENCRYPT_HOST=test.rolandw.dev
            - LETSENCRYPT_EMAIL=warburtonroland@gmail.com
            - VIRTUAL_PORT=3000
            - VIRTUAL_NETWORK=proxy-network
        ports:
            - 3000
        volumes:
            - ./content:/usr/src/app/content

networks:
    default:
        external:
            name: nginx-proxy
